# Generated by Django 4.1 on 2022-09-09 20:39

from django.db import migrations, models
import ocr.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('filename', models.CharField(max_length=125, unique=True)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=ocr.models.upload_to)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
